# Site settings
title: biioo
email: _
description: > # this means to ignore newlines until "baseurl:"
  Tips, techniques, and observations on the application of technology in the AEC industry (and other experiments).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.biioo.io" # the base hostname & protocol for your site

# Layout settings
header_type: default # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com

# Build settings
markdown: kramdown
